/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra;

import hr.algebra.view.adminview.EditArticlesPanel;
import hr.algebra.view.adminview.UploadArticlesPanel;
import hr.algebra.view.userview.ApprovedNewspaper;
import hr.algebra.view.userview.EditJournalistPanel;
import hr.algebra.view.userview.EditNewsPanel;
import hr.algebra.view.userview.EditNewspaperPanel;

/**
 *
 * @author Korisnik
 */
public class UserFrame extends javax.swing.JFrame {

    private static final String EDIT_NEWS_ARTICLES = "Edit News";
    private static final String EDIT_JOURNALIST_ARTICLES = "Edit Journalists";
    private static final String EDIT_NEWSPAPER = "Edit Newspaper";
    private static final String APPROVE_NEWSPAPER = "Approve Newspaper";
    /**
     * Creates new form UserFrame
     * @throws java.lang.Exception
     */
    public UserFrame() throws Exception {
        initComponents();
        configurePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpUserPanes = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 773));

        tpUserPanes.setPreferredSize(new java.awt.Dimension(1200, 773));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpUserPanes, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpUserPanes, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void configurePanels() throws Exception{
        tpUserPanes.add(EDIT_NEWS_ARTICLES, new EditNewsPanel());
        tpUserPanes.add(EDIT_JOURNALIST_ARTICLES, new EditJournalistPanel());
        tpUserPanes.add(EDIT_NEWSPAPER, new EditNewspaperPanel());
        tpUserPanes.add(APPROVE_NEWSPAPER, new ApprovedNewspaper());
    
}
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpUserPanes;
    // End of variables declaration//GEN-END:variables
}
